#pragma once

#define ABILITY_NONE 0
#define ABILITY_STENCH 1
#define ABILITY_DRIZZLE 2
#define ABILITY_SPEED_BOOST 3
#define ABILITY_BATTLE_ARMOR 4
#define ABILITY_STURDY 5
#define ABILITY_DAMP 6
#define ABILITY_LIMBER 7
#define ABILITY_SAND_VEIL 8
#define ABILITY_STATIC 9
#define ABILITY_VOLT_ABSORB 10
#define ABILITY_WATER_ABSORB 11
#define ABILITY_OBLIVIOUS 12
#define ABILITY_CLOUD_NINE 13
#define ABILITY_COMPOUND_EYES 14
#define ABILITY_INSOMNIA 15
#define ABILITY_COLOR_CHANGE 16
#define ABILITY_IMMUNITY 17
#define ABILITY_FLASH_FIRE 18
#define ABILITY_SHIELD_DUST 19
#define ABILITY_OWN_TEMPO 20
#define ABILITY_SUCTION_CUPS 21
#define ABILITY_INTIMIDATE 22
#define ABILITY_SHADOW_TAG 23
#define ABILITY_ROUGH_SKIN 24
#define ABILITY_WONDER_GUARD 25
#define ABILITY_LEVITATE 26
#define ABILITY_EFFECT_SPORE 27
#define ABILITY_SYNCHRONIZE 28
#define ABILITY_CLEAR_BODY 29
#define ABILITY_NATURAL_CURE 30
#define ABILITY_LIGHTNING_ROD 31
#define ABILITY_SERENE_GRACE 32
#define ABILITY_SWIFT_SWIM 33
#define ABILITY_CHLOROPHYLL 34
#define ABILITY_ILLUMINATE 35
#define ABILITY_TRACE 36
#define ABILITY_HUGE_POWER 37
#define ABILITY_POISON_POINT 38
#define ABILITY_INNER_FOCUS 39
#define ABILITY_MAGMA_ARMOR 40
#define ABILITY_WATER_VEIL 41
#define ABILITY_MAGNET_PULL 42
#define ABILITY_SOUNDPROOF 43
#define ABILITY_RAIN_DISH 44
#define ABILITY_SAND_STREAM 45
#define ABILITY_PRESSURE 46
#define ABILITY_THICK_FAT 47
#define ABILITY_EARLY_BIRD 48
#define ABILITY_FLAME_BODY 49
#define ABILITY_RUN_AWAY 50
#define ABILITY_KEEN_EYE 51
#define ABILITY_HYPER_CUTTER 52
#define ABILITY_PICKUP 53
#define ABILITY_TRUANT 54
#define ABILITY_HUSTLE 55
#define ABILITY_CUTE_CHARM 56
#define ABILITY_PLUS 57
#define ABILITY_MINUS 58
#define ABILITY_FORECAST 59
#define ABILITY_STICKY_HOLD 60
#define ABILITY_SHED_SKIN 61
#define ABILITY_GUTS 62
#define ABILITY_MARVEL_SCALE 63
#define ABILITY_LIQUID_OOZE 64
#define ABILITY_OVERGROW 65
#define ABILITY_BLAZE 66
#define ABILITY_TORRENT 67
#define ABILITY_SWARM 68
#define ABILITY_ROCK_HEAD 69
#define ABILITY_DROUGHT 70
#define ABILITY_ARENA_TRAP 71
#define ABILITY_VITAL_SPIRIT 72
#define ABILITY_WHITE_SMOKE 73
#define ABILITY_PURE_POWER 74
#define ABILITY_SHELL_ARMOR 75
#define ABILITY_AIR_LOCK 76

//gen 4
#define ABILITY_TANGLED_FEET 77
#define ABILITY_MOTOR_DRIVE 78
#define ABILITY_RIVALRY 79
#define ABILITY_STEADFAST 80
#define ABILITY_SNOW_CLOAK 81
#define ABILITY_GLUTTONY 82
#define ABILITY_ANGER_POINT 83
#define ABILITY_UNBURDEN 84
#define ABILITY_HEATPROOF 85
#define ABILITY_SIMPLE 86
#define ABILITY_DRY_SKIN 87
#define ABILITY_DOWNLOAD 88
#define ABILITY_IRON_FIST 89
#define ABILITY_POISON_HEAL 90
#define ABILITY_ADAPTABILITY 91
#define ABILITY_SKILL_LINK 92
#define ABILITY_HYDRATION 93
#define ABILITY_SOLAR_POWER 94
#define ABILITY_QUICK_FEET 95
#define ABILITY_NORMALIZE 96
#define ABILITY_SNIPER 97
#define ABILITY_MAGIC_GUARD 98
#define ABILITY_NO_GUARD 99
#define ABILITY_STALL 100
#define ABILITY_TECHNICIAN 101
#define ABILITY_LEAF_GUARD 102
#define ABILITY_KLUTZ 103
#define ABILITY_MOLD_BREAKER 104
#define ABILITY_SUPER_LUCK 105
#define ABILITY_AFTERMATH 106
#define ABILITY_ANTICIPATION 107
#define ABILITY_FOREWARN 108
#define ABILITY_UNAWARE 109
#define ABILITY_TINTED_LENS 110
#define ABILITY_FILTER 111
#define ABILITY_SLOW_START 112
#define ABILITY_SCRAPPY 113
#define ABILITY_STORM_DRAIN 114
#define ABILITY_ICE_BODY 115
#define ABILITY_SOLID_ROCK 116
#define ABILITY_SNOW_WARNING 117
#define ABILITY_HONEY_GATHER 118
#define ABILITY_FRISK 119
#define ABILITY_RECKLESS 120
#define ABILITY_MULTITYPE 121
#define ABILITY_FLOWER_GIFT 122
#define ABILITY_BAD_DREAMS 123

//new ability
#define ABILITY_SHEER_FORCE 125
#define ABILITY_CONTRARY 126        //唱反调
#define ABILITY_DEFIANT 128         //不服输
#define ABILITY_DEFEATIST 129       //软弱
#define ABILITY_HEALER 131          //治愈之心
#define ABILITY_FRIEND_GUARD 132    //友情防守
#define ABILITY_WEAK_ARMOR 133      //破碎铠甲
#define ABILITY_HEAVY_METAL 134     //重金属
#define ABILITY_LIGHT_METAL 135     //轻金属
#define ABILITY_MULTISCALE 136      //多重鳞片
#define ABILITY_TOXIC_BOOST 137     //毒暴走
#define ABILITY_FLARE_BOOST 138     //热暴走
#define ABILITY_HARVEST 139         //收获
#define ABILITY_MOODY 141           //性情不定
#define ABILITY_OVERCOAT 142        //防尘
#define ABILITY_POSION_TOUCH 143    //毒手
#define ABILITY_REGENERATOR 144     //再生力
#define ABILITY_BIG_PECKS 145       //健壮胸肌
#define ABILITY_SAND_RUSH 146       //拨沙
#define ABILITY_ANALYTIC 148        //分析
#define ABILITY_IMPOSTER 150        //变身者
#define ABILITY_INFILTRATOR 151     //穿透
#define ABILITY_MUMMY 152           //木乃伊
#define ABLITY_MOXIE 153            //自信过剩
#define ABILITY_JUSTFIED 154        //正义之心
#define ABILITY_RATTLED 155         //胆怯
#define ABILITY_MAGIC_BOUCE 156     //魔法镜
#define ABILITY_SAP_SIPPER 157      //食草
#define ABILITY_PRANKSTER 158       //恶作剧之心
#define ABILITY_SAND_FORCE 159      //砂之力
#define ABILITY_IRON_BARBS 160      //铁刺
#define ABILITY_DRAGONS_MAW 163     //原涡轮火焰，改为龙鄂
#define ABILITY_PROTEAN 168         //变幻自如
#define ABILITY_FUR_COAT 169        //毛皮大衣
#define ABILITY_COMPETITIVE 172     //好胜
#define ABILITY_STRONG_JAW 173      //强壮之鄂
#define ABILITY_REFRIGERATE 174     //冰冻皮肤
#define ABILIRT_MEGA_LAUNCHER 178   //超级炮台
#define ABILITY_GALE_WINGS 177      //疾风之翼
#define ABILITY_TOUGH_CLAWS 181     //硬爪
#define ABILITY_PIXILATE 182        //妖精皮肤
#define ABILITY_AERILATE 184        //飞行皮肤
#define ABILITY_GOOEY 183           //黏滑
#define ABILITY_DARK_AURA 186       //暗黑气场
#define ABILITY_FAIRY_AURA 187      //妖精气场
#define ABILITY_AURA_BREAK 188      //气场破坏
#define ABILITY_CHILLING_NEIGH 189  //原起始之海，改为苍白嘶鸣
#define ABILITY_GRIM_NEIGH 190      //原终结之地，改为漆黑嘶鸣
#define ABILITY_AS_ONE 191          //原气流，改为人马一体
#define ABILITY_WATER_BUBBLE 199    //水泡
#define ABILITY_STEEL_WORK 200      //钢能力者
#define ABILITY_SLUSH_RUSH 202      //滑雪
#define ABILITY_LONG_REACH 203      //远隔
#define ABILITY_GALVANIZE 206       //电气皮肤
#define ABILITY_TRANSISTOR 213      //原绝对睡眠，改为电晶体
#define ABILITY_QUEENLY_MAJESTY 214 //女王的威严
#define ABILITY_BATTERY 217         //蓄电池
#define ABILITY_FLUFFY 218          //毛茸茸
#define ABILIRT_DAZZLING 219        //鲜艳之躯
//#define ABILITY_SOUL_HEART 220      //魂心
#define ABILITY_TANGLING_HAIR 221   //卷发
#define ABILITY_HUGER_SWITCH 223    //饱了又饿
#define ABILITY_BEAST_BOOST 224     //异兽提升


#define ABILITY_SHADOW_SHIELD 231   //幻影防守
#define ABILITY_INTREPID_SWORD  234    //不饶之剑
#define ABILITY_DAUNTLESS_SHIELD 235 //不屈之盾
#define ABILITY_PUNK_ROCK 244       //庞克摇滚
#define ABILITY_POWER_SPOT 249      //能量点
#define ABILITY_STEELY_SPIRIT 252   //钢之意志
