#pragma once

//NARC files
#define ARC_PERSONAL 2
#define ARC_MON_PIC 4
#define ARC_OTHER_MON_PIC 114

//能力变化
#define SEQ_STATE_CHANGE 12

//形态变化
#define SEQ_FORM_CHANGE 262

#define SEQ_DARK_AURA 297
#define SEQ_FAIRY_AURA 298
#define SEQ_AURA_BREAK 299
#define SEQ_MUMMY 300
#define SEQ_WEAK_ARMOR 301
#define SEQ_HARVEST 306
#define SEQ_MOODY 307

//mega种族值文件
#define BASE_MEGA_VENUSAUR_DATA MEGA_VENUSAUR


//MEGA图片
#define FONTPIC_MEGA_VENUSAUR MEGA_VENUSAUR * 6 + 4
#define PAL_MEGA_VENUSAUR MEGA_VENUSAUR * 6